server:
  port: 8081
  servlet:
    context-path: /@project.artifactId@
datasource:
  pgs:
    jdbcUrl: jdbc:postgresql://${DB_URL}:5432/postgres
    password: 123456
    username: postgres
user:
  uri: ${USER_URI}